### PR TITLE
Refactor: Change grades data type from u32 to f32 

### PR DESCRIPTION
**Pull request by unpeturbed**
This pull request changes the data type for grades from `u32` to `f32` to allow for greater precision, particularly when working with fractional grade values.

**Reason:**
The current implementation uses `u32` for grades, which restricts the precision to whole numbers. To support fractional grades and improve accuracy in calculations, `f32` is more appropriate.

**Changes Made:**
- Updated the grades field from u32 to f32 in:
    `src/main.rs`
- Adjusted all related calculations and logic to handle `f32`.

### CODE REVIEW

**Comment by fnabinash** [comment]
Did you push it `-f`?

If yes, please pull all the changes first then refactor it and raise a pr again.

**Comment by unpeturbed** [comment]
> Did you push it `-f`?
> 
> If yes, please pull all the changes first then refactor it and raise a pr again.

Not sure I get what you mean

**Comment by fnabinash** [comment]
While you are pushing code did you use the -f(means with force command)?

Because I made some changes to this repo, I hope you did not pull the changes.

Before pulling you pushed your code to the main branch and it failed then you again did it with force(-f).

If yes, please pull the changes first then raise the pr again. Because it rewrites the history.

**Comment by unpeturbed** [comment]
> While you are pushing code did you use the -f(means with force command)?
> 
> Because I made some changes to this repo, I hope you did not pull the changes.
> 
> Before pulling you pushed your code to the main branch and it failed then you again did it with force(-f).
> 
> If yes, please pull the changes first then raise the pr again. Because it rewrites the history.

I get you. now, i didn't force push. I'll try to rectify here anyway

**Pull request closed without merging**
