### PR TITLE
Add Simple "Hello, World!" Program with Unit Test

### PR DESCRIPTION
**Pull request by unpeturbed**
Changes:

- **main.rs:**
       Added a new function `print_hello` so unit test could be written.
       The print_hello() function returns the string `Hello, world!` as a String.

- **Documentation:**
        Added documentation comments to the main function and `print_hello()` function to clarify their purpose.
        Used Rust doc-comments `///` to provide an overview of each function.

- **Unit Test:**
       Included a unit test in a `#[cfg(test)]` module to validate that the `print_hello()` function correctly returns the expected 
       string `Hello, world!`.

- **Testing:**
       Running `cargo test` successfully passes all tests and validates that the program outputs the correct string.

- **Output:**
      `Hello, world!`

### CODE REVIEW

**Comment by unpeturbed** [comment]
Regarding this. Do I keep pushing codes or I'm meant to only solve?

**Comment by fnabinash** [comment]
I think you should solve your own exercise and write documentation for the practice branch. We will feature your solutions under every exercise that you have solved. 

Means,

Imagine you just solved the first exercise of `struct` then in the `structs_01` documentation file, we will add a link to your solution. So that newcomers can have different ways to solve the exercises.

The plan is that every exercise(i.e. `src/main.rs` file) has the problem statement then a link to documentation then the `main` function. If the user is unable to understand the problem or needs some assistance then he/she will click the link and go to the documentation.

On documentation he/she will find more context on the problem then some useful links to resources to know more about that particular concept then some links to the solutions that other people have solved.

I think you got the idea. If not feel free to ask anything. 

Also, give some feedback on this idea.

**Comment by unpeturbed** [comment]
I get now. That's great then. Thank you

**Comment by fnabinash** [comment]
I think we should close this pr?

**Pull request closed without merging**
